USE [master]
GO
/****** Object:  Database [Productos]    Script Date: 11/04/2022 6:13:19 p. m. ******/
CREATE DATABASE [Productos]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Productos', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\Productos.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'Productos_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\Productos_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO
ALTER DATABASE [Productos] SET COMPATIBILITY_LEVEL = 150
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Productos].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [Productos] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [Productos] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [Productos] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [Productos] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [Productos] SET ARITHABORT OFF 
GO
ALTER DATABASE [Productos] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [Productos] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [Productos] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [Productos] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [Productos] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [Productos] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [Productos] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [Productos] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [Productos] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [Productos] SET  DISABLE_BROKER 
GO
ALTER DATABASE [Productos] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [Productos] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [Productos] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [Productos] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [Productos] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [Productos] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [Productos] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [Productos] SET RECOVERY FULL 
GO
ALTER DATABASE [Productos] SET  MULTI_USER 
GO
ALTER DATABASE [Productos] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [Productos] SET DB_CHAINING OFF 
GO
ALTER DATABASE [Productos] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [Productos] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [Productos] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [Productos] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
EXEC sys.sp_db_vardecimal_storage_format N'Productos', N'ON'
GO
ALTER DATABASE [Productos] SET QUERY_STORE = OFF
GO
USE [Productos]
GO
/****** Object:  Table [dbo].[Categoria]    Script Date: 11/04/2022 6:13:19 p. m. ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Categoria](
	[Id_Categoria] [int] IDENTITY(1,1) NOT NULL,
	[Nombre] [varchar](500) NULL,
PRIMARY KEY CLUSTERED 
(
	[Id_Categoria] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Producto]    Script Date: 11/04/2022 6:13:19 p. m. ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Producto](
	[Id_Producto] [int] IDENTITY(1,1) NOT NULL,
	[Nombre] [varchar](500) NOT NULL,
	[Descripcion] [varchar](1000) NOT NULL,
	[CodCategoria] [int] NOT NULL,
	[Imagen] [varchar](500) NULL,
PRIMARY KEY CLUSTERED 
(
	[Id_Producto] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[Producto] ADD  DEFAULT ('') FOR [Descripcion]
GO
ALTER TABLE [dbo].[Producto]  WITH CHECK ADD FOREIGN KEY([CodCategoria])
REFERENCES [dbo].[Categoria] ([Id_Categoria])
GO
ALTER TABLE [dbo].[Producto]  WITH CHECK ADD FOREIGN KEY([CodCategoria])
REFERENCES [dbo].[Categoria] ([Id_Categoria])
GO
ALTER TABLE [dbo].[Producto]  WITH CHECK ADD FOREIGN KEY([CodCategoria])
REFERENCES [dbo].[Categoria] ([Id_Categoria])
GO
USE [master]
GO
ALTER DATABASE [Productos] SET  READ_WRITE 
GO
